#! /bin/bash

sudo cgcreate -a crow:crow -t crow:crow -g memory:test_crypto
echo 1M > /sys/fs/cgroup/memory/test_crypto/memory.limit_in_bytes
echo 1M > /sys/fs/cgroup/memory/test_crypto/memory.memsw.limit_in_bytes
cgexec -g memory:test_crypto ./encrypt2 $@

