#!/usr/bin/env python3
import sys

with open(sys.argv[1], 'rb') as in_file:
    data = in_file.read()       # data is of type "bytes"
    hexdata = data.hex()              # hexdata is a string of hex digits
    bindata = bytes.fromhex(hexdata)  # bindata should be the same as data

n = 32
chunks = [hexdata[i:i+n] for i in range(0, len(hexdata), n)]

# !!!Edit to simulate my acc
#chunks[19] = "15751e9f8201e67c0b535580f5c0ff00"

occ_map = {}
for chunk in chunks:
    if chunk in occ_map:
        occ_map[chunk] += 1
    else:
        occ_map[chunk] = 1

de_map = {}

# Assume first cmd is BALANCE and next seen is TRANSFER
scan = 0
correct = False
de_map[chunks[0]] = "BALANCE"
while scan < len(chunks) and len(de_map) < 4:
    if chunks[scan] in de_map:
        if de_map[chunks[scan]] == "BALANCE":
            scan += 2
        elif de_map[chunks[scan]] == "INVOICE":
            scan += 4
        elif de_map[chunks[scan]] == "TRANSFER":
            scan += 5
    else: 
        if "TRANSFER" in de_map.values():
            de_map[chunks[scan]] = "INVOICE"
        else:
            de_map[chunks[scan]] = "TRANSFER"

# Check if previous was correct
if scan == len(chunks):
    correct = True
else: # Assume first transact was BALANCE and next seen is INVOICE
    de_map = {}
    scan = 0
    de_map[chunks[0]] = "BALANCE"
    while scan < len(chunks) and len(de_map) < 4:
        if chunks[scan] in de_map:
            if de_map[chunks[scan]] == "BALANCE":
                scan += 2
            elif de_map[chunks[scan]] == "INVOICE":
                scan += 4
            elif de_map[chunks[scan]] == "TRANSFER":
                scan += 5
        else: 
            if "INVOICE" in de_map.values():
                de_map[chunks[scan]] = "TRANSFER"
            else:
                de_map[chunks[scan]] = "INVOICE"


# Check if previous was correct
if scan == len(chunks):
    correct = True
else: # Assume first transact was TRANSFER and next seen is INVOICE
    de_map = {}
    scan = 0
    de_map[chunks[0]] = "TRANSFER"
    while scan < len(chunks) and len(de_map) < 4:
        if chunks[scan] in de_map:
            if de_map[chunks[scan]] == "BALANCE":
                scan += 2
            elif de_map[chunks[scan]] == "INVOICE":
                scan += 4
            elif de_map[chunks[scan]] == "TRANSFER":
                scan += 5
        else: 
            if "INVOICE" in de_map.values():
                de_map[chunks[scan]] = "BALANCE"
            else:
                de_map[chunks[scan]] = "INVOICE"

# Check if previous was correct
if scan == len(chunks):
    correct = True
else: # Assume first transact was TRANSFER and next seen is BALANCE
    de_map = {}
    scan = 0
    de_map[chunks[0]] = "TRANSFER"
    while scan < len(chunks) and len(de_map) < 4:
        if chunks[scan] in de_map:
            if de_map[chunks[scan]] == "BALANCE":
                scan += 2
            elif de_map[chunks[scan]] == "INVOICE":
                scan += 4
            elif de_map[chunks[scan]] == "TRANSFER":
                scan += 5
        else: 
            if "BALANCE" in de_map.values():
                de_map[chunks[scan]] = "INVOICE"
            else:
                de_map[chunks[scan]] = "BALANCE"

# Check if previous was correct
if scan == len(chunks):
    correct = True
else: # Assume first transact was INVOICE and next seen is BALANCE
    de_map = {}
    scan = 0
    de_map[chunks[0]] = "INVOICE"
    while scan < len(chunks) and len(de_map) < 4:
        if chunks[scan] in de_map:
            if de_map[chunks[scan]] == "BALANCE":
                scan += 2
            elif de_map[chunks[scan]] == "INVOICE":
                scan += 4
            elif de_map[chunks[scan]] == "TRANSFER":
                scan += 5
        else: 
            if "BALANCE" in de_map.values():
                de_map[chunks[scan]] = "TRANSFER"
            else:
                de_map[chunks[scan]] = "BALANCE"

# Check if previous was correct
if scan == len(chunks):
    correct = True
else: # Assume first transact was INVOICE and next seen is TRANSFER
    de_map = {}
    scan = 0
    de_map[chunks[0]] = "INVOICE"
    while scan < len(chunks) and len(de_map) < 4:
        if chunks[scan] in de_map:
            if de_map[chunks[scan]] == "BALANCE":
                scan += 2
            elif de_map[chunks[scan]] == "INVOICE":
                scan += 4
            elif de_map[chunks[scan]] == "TRANSFER":
                scan += 5
        else: 
            if "TRANSFER" in de_map.values():
                de_map[chunks[scan]] = "BALANCE"
            else:
                de_map[chunks[scan]] = "TRANSFER"

for index, line in enumerate(chunks):
    if line in de_map:
        print(de_map[line])

repeat = ""
for index, line in enumerate(chunks):
    if line in de_map:
        if de_map[line] == "TRANSFER":
            if occ_map[chunks[index + 3]] == 1:
                # This is the transfer to me since this acc only appears once
                repeat = chunks[index:index+5]
                break

# Extend chunks by repeat
chunks.extend(repeat)
# Convert chunks into hex then to binary
hex_out = "".join(chunks)
#bin_out = binascii.unhexlify(hex_out)
bin_out = bytes.fromhex(hex_out)

# Print to output file
f = open("task2.out", "wb")
f.write(bin_out)
f.close()

